### ISSUE TITLE
Bulbs getting Adopted after already adopting

### ISSUE THREAD

**Issue by Exit2Studios** [KaufHA/kauf-rgbww-bulbs#5]
I've gone through and updated the firmware on some bulbs that shipped pre 1.72.  I adopted them into esphome and changed the config, renamed the yaml file, etc.  However, I'm getting the following duplicate entries for each of those bulbs (and unable to adopt if I try).  How do I get this to go away?
![image](https://user-images.githubusercontent.com/16908875/153464814-699b75ca-27e2-481d-9594-bc0ca9f6b70f.png)

**Comment by KaufHA** [comment]
Did you compile the firmware and flash to the bulb?  If not, then the old firmware is still running and being found in addition to the yaml file.

Here's what I have when I adopt but don't install:

![image](https://user-images.githubusercontent.com/89616381/153479824-a8657ed6-3550-44af-a05e-892625a11981.png) ![image](https://user-images.githubusercontent.com/89616381/153479859-80ab8691-beba-4998-ad92-b910a88dc482.png)

The green one is shown due to the firmware running on the network broadcasting its dashboard import capability.  The red one is due to a yaml file in the config directory.  It's red because there is no corresponding device found on the network.  Only once I "update" the adopted bulb then ESPHome doesn't see the old firmware available to adopt.

If you did already flash new firmware to the bulb then I'd try deleting the ".esphome" folder within the esphome config directory.  Maybe something is cached funny.

**Comment by KaufHA** [comment]
Maybe restart the esphome addon or dashboard as well when you delete .esphome
